/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AccessReferenceRouteImport } from './routes/access/$reference'
import { Route as ClassesIndexRouteImport } from './routes/classes/index'
import { Route as ClassesSlugRouteImport } from './routes/classes/$slug'
import { Route as ProgramsOrynSoundzRouteImport } from './routes/programs/oryn-soundz'
import { Route as ProgramsOrynSoundzSlugRouteImport } from './routes/programs/oryn-soundz/$slug'
import { Route as ApiPaymentsPaystackInitializeRouteImport } from './routes/api/payments/paystack/initialize'
import { Route as ApiPaymentsPaystackVerifyRouteImport } from './routes/api/payments/paystack/verify'
import { Route as ApiPaymentsPaystackWebhookRouteImport } from './routes/api/payments/paystack/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessReferenceRoute = AccessReferenceRouteImport.update({
  id: '/access/$reference',
  path: '/access/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIndexRoute = ClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesSlugRoute = ClassesSlugRouteImport.update({
  id: '/classes/$slug',
  path: '/classes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsOrynSoundzRoute = ProgramsOrynSoundzRouteImport.update({
  id: '/programs/oryn-soundz',
  path: '/programs/oryn-soundz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsOrynSoundzSlugRoute = ProgramsOrynSoundzSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProgramsOrynSoundzRoute,
} as any)
const ApiPaymentsPaystackInitializeRoute =
  ApiPaymentsPaystackInitializeRouteImport.update({
    id: '/api/payments/paystack/initialize',
    path: '/api/payments/paystack/initialize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentsPaystackVerifyRoute =
  ApiPaymentsPaystackVerifyRouteImport.update({
    id: '/api/payments/paystack/verify',
    path: '/api/payments/paystack/verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentsPaystackWebhookRoute =
  ApiPaymentsPaystackWebhookRouteImport.update({
    id: '/api/payments/paystack/webhook',
    path: '/api/payments/paystack/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/access/$reference': typeof AccessReferenceRoute
  '/classes/$slug': typeof ClassesSlugRoute
  '/programs/oryn-soundz': typeof ProgramsOrynSoundzRouteWithChildren
  '/classes/': typeof ClassesIndexRoute
  '/programs/oryn-soundz/$slug': typeof ProgramsOrynSoundzSlugRoute
  '/api/payments/paystack/initialize': typeof ApiPaymentsPaystackInitializeRoute
  '/api/payments/paystack/verify': typeof ApiPaymentsPaystackVerifyRoute
  '/api/payments/paystack/webhook': typeof ApiPaymentsPaystackWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/access/$reference': typeof AccessReferenceRoute
  '/classes/$slug': typeof ClassesSlugRoute
  '/programs/oryn-soundz': typeof ProgramsOrynSoundzRouteWithChildren
  '/classes': typeof ClassesIndexRoute
  '/programs/oryn-soundz/$slug': typeof ProgramsOrynSoundzSlugRoute
  '/api/payments/paystack/initialize': typeof ApiPaymentsPaystackInitializeRoute
  '/api/payments/paystack/verify': typeof ApiPaymentsPaystackVerifyRoute
  '/api/payments/paystack/webhook': typeof ApiPaymentsPaystackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/access/$reference': typeof AccessReferenceRoute
  '/classes/$slug': typeof ClassesSlugRoute
  '/programs/oryn-soundz': typeof ProgramsOrynSoundzRouteWithChildren
  '/classes/': typeof ClassesIndexRoute
  '/programs/oryn-soundz/$slug': typeof ProgramsOrynSoundzSlugRoute
  '/api/payments/paystack/initialize': typeof ApiPaymentsPaystackInitializeRoute
  '/api/payments/paystack/verify': typeof ApiPaymentsPaystackVerifyRoute
  '/api/payments/paystack/webhook': typeof ApiPaymentsPaystackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/privacy'
    | '/terms'
    | '/access/$reference'
    | '/classes/$slug'
    | '/programs/oryn-soundz'
    | '/classes/'
    | '/programs/oryn-soundz/$slug'
    | '/api/payments/paystack/initialize'
    | '/api/payments/paystack/verify'
    | '/api/payments/paystack/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/privacy'
    | '/terms'
    | '/access/$reference'
    | '/classes/$slug'
    | '/programs/oryn-soundz'
    | '/classes'
    | '/programs/oryn-soundz/$slug'
    | '/api/payments/paystack/initialize'
    | '/api/payments/paystack/verify'
    | '/api/payments/paystack/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/privacy'
    | '/terms'
    | '/access/$reference'
    | '/classes/$slug'
    | '/programs/oryn-soundz'
    | '/classes/'
    | '/programs/oryn-soundz/$slug'
    | '/api/payments/paystack/initialize'
    | '/api/payments/paystack/verify'
    | '/api/payments/paystack/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AccessReferenceRoute: typeof AccessReferenceRoute
  ClassesSlugRoute: typeof ClassesSlugRoute
  ProgramsOrynSoundzRoute: typeof ProgramsOrynSoundzRouteWithChildren
  ClassesIndexRoute: typeof ClassesIndexRoute
  ApiPaymentsPaystackInitializeRoute: typeof ApiPaymentsPaystackInitializeRoute
  ApiPaymentsPaystackVerifyRoute: typeof ApiPaymentsPaystackVerifyRoute
  ApiPaymentsPaystackWebhookRoute: typeof ApiPaymentsPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access/$reference': {
      id: '/access/$reference'
      path: '/access/$reference'
      fullPath: '/access/$reference'
      preLoaderRoute: typeof AccessReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/': {
      id: '/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof ClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$slug': {
      id: '/classes/$slug'
      path: '/classes/$slug'
      fullPath: '/classes/$slug'
      preLoaderRoute: typeof ClassesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/oryn-soundz': {
      id: '/programs/oryn-soundz'
      path: '/programs/oryn-soundz'
      fullPath: '/programs/oryn-soundz'
      preLoaderRoute: typeof ProgramsOrynSoundzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/oryn-soundz/$slug': {
      id: '/programs/oryn-soundz/$slug'
      path: '/$slug'
      fullPath: '/programs/oryn-soundz/$slug'
      preLoaderRoute: typeof ProgramsOrynSoundzSlugRouteImport
      parentRoute: typeof ProgramsOrynSoundzRoute
    }
    '/api/payments/paystack/initialize': {
      id: '/api/payments/paystack/initialize'
      path: '/api/payments/paystack/initialize'
      fullPath: '/api/payments/paystack/initialize'
      preLoaderRoute: typeof ApiPaymentsPaystackInitializeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/paystack/verify': {
      id: '/api/payments/paystack/verify'
      path: '/api/payments/paystack/verify'
      fullPath: '/api/payments/paystack/verify'
      preLoaderRoute: typeof ApiPaymentsPaystackVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/paystack/webhook': {
      id: '/api/payments/paystack/webhook'
      path: '/api/payments/paystack/webhook'
      fullPath: '/api/payments/paystack/webhook'
      preLoaderRoute: typeof ApiPaymentsPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProgramsOrynSoundzRouteChildren {
  ProgramsOrynSoundzSlugRoute: typeof ProgramsOrynSoundzSlugRoute
}

const ProgramsOrynSoundzRouteChildren: ProgramsOrynSoundzRouteChildren = {
  ProgramsOrynSoundzSlugRoute: ProgramsOrynSoundzSlugRoute,
}

const ProgramsOrynSoundzRouteWithChildren =
  ProgramsOrynSoundzRoute._addFileChildren(ProgramsOrynSoundzRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AccessReferenceRoute: AccessReferenceRoute,
  ClassesSlugRoute: ClassesSlugRoute,
  ProgramsOrynSoundzRoute: ProgramsOrynSoundzRouteWithChildren,
  ClassesIndexRoute: ClassesIndexRoute,
  ApiPaymentsPaystackInitializeRoute: ApiPaymentsPaystackInitializeRoute,
  ApiPaymentsPaystackVerifyRoute: ApiPaymentsPaystackVerifyRoute,
  ApiPaymentsPaystackWebhookRoute: ApiPaymentsPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
